// Code generated by gitverse-codegen. DO NOT EDIT.

package gitverse

import (
	"context"
	"fmt"
	"net/url"
)

// ListOrgRunners Returns a list of self-hosted runners for an organization
func (c *Client) ListOrgRunners(ctx context.Context, org string, opts *QueryOptions) (ActionRunners, error) {
	path := fmt.Sprintf("/orgs/%s/actions/runners", org)
	query := url.Values{}
	if opts != nil {
		if opts.Page != 0 {
			query.Set("page", fmt.Sprintf("%d", opts.Page))
		}
		if opts.PerPage != 0 {
			query.Set("per_page", fmt.Sprintf("%d", opts.PerPage))
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero ActionRunners
		return zero, err
	}
	return decodeResponse[ActionRunners](resp)
}

// GetOrgRunner Gets a specific self-hosted runner for an organization
func (c *Client) GetOrgRunner(ctx context.Context, org string, runner_id float64) (ActionRunner, error) {
	path := fmt.Sprintf("/orgs/%s/actions/runners/%v", org, runner_id)
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		var zero ActionRunner
		return zero, err
	}
	return decodeResponse[ActionRunner](resp)
}

// DeleteOrgRunner Deletes a specific self-hosted runner from the organization
func (c *Client) DeleteOrgRunner(ctx context.Context, org string, runner_id float64) error {
	path := fmt.Sprintf("/orgs/%s/actions/runners/%v", org, runner_id)
	resp, err := c.delete(ctx, path, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// CreateOrgRunnerRegistrationToken Creates a registration token for an
// organization runner
func (c *Client) CreateOrgRunnerRegistrationToken(ctx context.Context, org string) (RegistrationToken, error) {
	path := fmt.Sprintf("/orgs/%s/actions/runners/registration-token", org)
	resp, err := c.post(ctx, path, nil)
	if err != nil {
		var zero RegistrationToken
		return zero, err
	}
	return decodeResponse[RegistrationToken](resp)
}

// ListOrgVariables List organization variables
func (c *Client) ListOrgVariables(ctx context.Context, org string, opts *QueryOptions) (VariableList, error) {
	path := fmt.Sprintf("/orgs/%s/actions/variables", org)
	query := url.Values{}
	if opts != nil {
		if opts.PerPage != 0 {
			query.Set("per_page", fmt.Sprintf("%d", opts.PerPage))
		}
		if opts.Page != 0 {
			query.Set("page", fmt.Sprintf("%d", opts.Page))
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero VariableList
		return zero, err
	}
	return decodeResponse[VariableList](resp)
}

// CreateOrgVariable Create an organization variable
func (c *Client) CreateOrgVariable(ctx context.Context, org string, params CreateVariableParams) error {
	path := fmt.Sprintf("/orgs/%s/actions/variables", org)
	resp, err := c.post(ctx, path, params)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// GetOrgVariable Get an organization variable
func (c *Client) GetOrgVariable(ctx context.Context, org string, name string) (Variable, error) {
	path := fmt.Sprintf("/orgs/%s/actions/variables/%s", org, name)
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		var zero Variable
		return zero, err
	}
	return decodeResponse[Variable](resp)
}

// UpdateOrgVariable Update an organization variable
func (c *Client) UpdateOrgVariable(ctx context.Context, org string, name string, params CreateVariableParams) error {
	path := fmt.Sprintf("/orgs/%s/actions/variables/%s", org, name)
	resp, err := c.patch(ctx, path, params)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// DeleteOrgVariable Delete an organization variable
func (c *Client) DeleteOrgVariable(ctx context.Context, org string, name string) error {
	path := fmt.Sprintf("/orgs/%s/actions/variables/%s", org, name)
	resp, err := c.delete(ctx, path, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// ListArtifacts Returns a list of artifacts in the repository
func (c *Client) ListArtifacts(ctx context.Context, owner string, repo string, opts *QueryOptions) (ActionArtifactList, error) {
	path := fmt.Sprintf("/repos/%s/%s/actions/artifacts", owner, repo)
	query := url.Values{}
	if opts != nil {
		if opts.Page != 0 {
			query.Set("page", fmt.Sprintf("%d", opts.Page))
		}
		if opts.PerPage != 0 {
			query.Set("per_page", fmt.Sprintf("%d", opts.PerPage))
		}
		if opts.Name != "" {
			query.Set("name", opts.Name)
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero ActionArtifactList
		return zero, err
	}
	return decodeResponse[ActionArtifactList](resp)
}

// GetArtifact Returns a specific artifact from the repository
func (c *Client) GetArtifact(ctx context.Context, owner string, repo string, artifact_id string) (ActionArtifact, error) {
	path := fmt.Sprintf("/repos/%s/%s/actions/artifacts/%s", owner, repo, artifact_id)
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		var zero ActionArtifact
		return zero, err
	}
	return decodeResponse[ActionArtifact](resp)
}

// DeleteArtifact Deletes a specific artifact
func (c *Client) DeleteArtifact(ctx context.Context, owner string, repo string, artifact_id string) error {
	path := fmt.Sprintf("/repos/%s/%s/actions/artifacts/%s", owner, repo, artifact_id)
	resp, err := c.delete(ctx, path, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// DownloadArtifact Downloads a specific artifact as a ZIP archive
func (c *Client) DownloadArtifact(ctx context.Context, owner string, repo string, artifact_id string) error {
	path := fmt.Sprintf("/repos/%s/%s/actions/artifacts/%s/zip", owner, repo, artifact_id)
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// DownloadArtifactRaw Downloads the artifact ZIP archive directly
func (c *Client) DownloadArtifactRaw(ctx context.Context, owner string, repo string, artifact_id string) (string, error) {
	path := fmt.Sprintf("/repos/%s/%s/actions/artifacts/%s/zip/raw", owner, repo, artifact_id)
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		var zero string
		return zero, err
	}
	return decodeResponse[string](resp)
}

// CreateActionLink Adds a link to an action run
func (c *Client) CreateActionLink(ctx context.Context, owner string, repo string, params CreateActionLinkParams) (ActionLink, error) {
	path := fmt.Sprintf("/repos/%s/%s/actions/links", owner, repo)
	resp, err := c.post(ctx, path, params)
	if err != nil {
		var zero ActionLink
		return zero, err
	}
	return decodeResponse[ActionLink](resp)
}

// ListRepoRunners Returns a list of runners for the repository
func (c *Client) ListRepoRunners(ctx context.Context, owner string, repo string, opts *QueryOptions) (ActionRunners, error) {
	path := fmt.Sprintf("/repos/%s/%s/actions/runners", owner, repo)
	query := url.Values{}
	if opts != nil {
		if opts.Page != 0 {
			query.Set("page", fmt.Sprintf("%d", opts.Page))
		}
		if opts.PerPage != 0 {
			query.Set("per_page", fmt.Sprintf("%d", opts.PerPage))
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero ActionRunners
		return zero, err
	}
	return decodeResponse[ActionRunners](resp)
}

// GetRepoRunner Gets a specific runner for a repository
func (c *Client) GetRepoRunner(ctx context.Context, owner string, repo string, runner_id float64) (ActionRunner, error) {
	path := fmt.Sprintf("/repos/%s/%s/actions/runners/%v", owner, repo, runner_id)
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		var zero ActionRunner
		return zero, err
	}
	return decodeResponse[ActionRunner](resp)
}

// DeleteRepoRunner Deletes a specific self-hosted runner from the repository
func (c *Client) DeleteRepoRunner(ctx context.Context, owner string, repo string, runner_id float64) error {
	path := fmt.Sprintf("/repos/%s/%s/actions/runners/%v", owner, repo, runner_id)
	resp, err := c.delete(ctx, path, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// CreateRepoRunnerRegistrationToken Creates a registration token for a repository
// runner
func (c *Client) CreateRepoRunnerRegistrationToken(ctx context.Context, owner string, repo string) (RegistrationToken, error) {
	path := fmt.Sprintf("/repos/%s/%s/actions/runners/registration-token", owner, repo)
	resp, err := c.post(ctx, path, nil)
	if err != nil {
		var zero RegistrationToken
		return zero, err
	}
	return decodeResponse[RegistrationToken](resp)
}

// ListRepoVariables List repository variables
func (c *Client) ListRepoVariables(ctx context.Context, owner string, repo string, opts *QueryOptions) (VariableList, error) {
	path := fmt.Sprintf("/repos/%s/%s/actions/variables", owner, repo)
	query := url.Values{}
	if opts != nil {
		if opts.PerPage != 0 {
			query.Set("per_page", fmt.Sprintf("%d", opts.PerPage))
		}
		if opts.Page != 0 {
			query.Set("page", fmt.Sprintf("%d", opts.Page))
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero VariableList
		return zero, err
	}
	return decodeResponse[VariableList](resp)
}

// CreateRepoVariable Create a repository variable
func (c *Client) CreateRepoVariable(ctx context.Context, owner string, repo string, params CreateVariableParams) error {
	path := fmt.Sprintf("/repos/%s/%s/actions/variables", owner, repo)
	resp, err := c.post(ctx, path, params)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// GetRepoVariable Get a repository variable
func (c *Client) GetRepoVariable(ctx context.Context, owner string, repo string, name string) (Variable, error) {
	path := fmt.Sprintf("/repos/%s/%s/actions/variables/%s", owner, repo, name)
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		var zero Variable
		return zero, err
	}
	return decodeResponse[Variable](resp)
}

// UpdateRepoVariable Update a repository variable
func (c *Client) UpdateRepoVariable(ctx context.Context, owner string, repo string, name string, params CreateVariableParams) error {
	path := fmt.Sprintf("/repos/%s/%s/actions/variables/%s", owner, repo, name)
	resp, err := c.patch(ctx, path, params)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// DeleteRepoVariable Delete a repository variable
func (c *Client) DeleteRepoVariable(ctx context.Context, owner string, repo string, name string) error {
	path := fmt.Sprintf("/repos/%s/%s/actions/variables/%s", owner, repo, name)
	resp, err := c.delete(ctx, path, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// GetWorkflowDispatchInputs Get workflow_dispatch parameters
func (c *Client) GetWorkflowDispatchInputs(ctx context.Context, owner string, repo string, workflow string, opts *QueryOptions) (WorkflowDispatchInputList, error) {
	path := fmt.Sprintf("/repos/%s/%s/actions/workflows/%s/dispatches", owner, repo, workflow)
	query := url.Values{}
	if opts != nil {
		if opts.Branch != "" {
			query.Set("branch", opts.Branch)
		}
		if opts.Tag != "" {
			query.Set("tag", opts.Tag)
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero WorkflowDispatchInputList
		return zero, err
	}
	return decodeResponse[WorkflowDispatchInputList](resp)
}

// DispatchWorkflow Trigger workflow_dispatch
func (c *Client) DispatchWorkflow(ctx context.Context, owner string, repo string, workflow string, params interface{}, opts *QueryOptions) error {
	path := fmt.Sprintf("/repos/%s/%s/actions/workflows/%s/dispatches", owner, repo, workflow)
	query := url.Values{}
	if opts != nil {
		if opts.Branch != "" {
			query.Set("branch", opts.Branch)
		}
		if opts.Tag != "" {
			query.Set("tag", opts.Tag)
		}
	}
	resp, err := c.post(ctx, path, params)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}
