// Code generated by gitverse-codegen. DO NOT EDIT.

// Package gitverse предоставляет клиент для работы с GitVerse API.
//
// Пример использования:
//
//	client := gitverse.NewClient(gitverse.ClientConfig{
//		Token: "your-token",
//	})
//
//	user, err := client.GetUser(context.Background(), "username")
//	if err != nil {
//		log.Fatal(err)
//	}
//	fmt.Println(user.Login)
package gitverse
