// Code generated by gitverse-codegen. DO NOT EDIT.

package gitverse

import (
	"context"
	"fmt"
	"net/url"
)

// ListEmails Get user email addresses
func (c *Client) ListEmails(ctx context.Context, opts *QueryOptions) ([]Email, error) {
	path := "/user/emails"
	query := url.Values{}
	if opts != nil {
		if opts.Page != 0 {
			query.Set("page", fmt.Sprintf("%d", opts.Page))
		}
		if opts.PerPage != 0 {
			query.Set("per_page", fmt.Sprintf("%d", opts.PerPage))
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero []Email
		return zero, err
	}
	return decodeResponse[[]Email](resp)
}

// CreateEmails Add email addresses
func (c *Client) CreateEmails(ctx context.Context, params CreateEmailParams) ([]Email, error) {
	path := "/user/emails"
	resp, err := c.post(ctx, path, params)
	if err != nil {
		var zero []Email
		return zero, err
	}
	return decodeResponse[[]Email](resp)
}

// DeleteEmails Delete email addresses
func (c *Client) DeleteEmails(ctx context.Context, params DeleteEmailParams) error {
	path := "/user/emails"
	resp, err := c.delete(ctx, path, params)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}
