// Code generated by gitverse-codegen. DO NOT EDIT.

package gitverse

// ContentType представляет возможные значения для ContentType
type ContentType string

const (
	ContentTypeDir ContentType = "dir"
	ContentTypeFile ContentType = "file"
)

// IssueState представляет возможные значения для IssueState
type IssueState string

const (
	IssueStateClosed IssueState = "closed"
	IssueStateOpen IssueState = "open"
)

// PullRequestSortCriteria представляет возможные значения для
// PullRequestSortCriteria
type PullRequestSortCriteria string

const (
	PullRequestSortCriteriaCreated PullRequestSortCriteria = "created"
	PullRequestSortCriteriaLongRunning PullRequestSortCriteria = "long-running"
	PullRequestSortCriteriaPopularity PullRequestSortCriteria = "popularity"
	PullRequestSortCriteriaUpdated PullRequestSortCriteria = "updated"
)

// PullRequestSortDirection представляет возможные значения для
// PullRequestSortDirection
type PullRequestSortDirection string

const (
	PullRequestSortDirectionAsc PullRequestSortDirection = "asc"
	PullRequestSortDirectionDesc PullRequestSortDirection = "desc"
)

// PullRequestState представляет возможные значения для PullRequestState
type PullRequestState string

const (
	PullRequestStateClosed PullRequestState = "closed"
	PullRequestStateOpen PullRequestState = "open"
)

// PullRequestStateFilter представляет возможные значения для
// PullRequestStateFilter
type PullRequestStateFilter string

const (
	PullRequestStateFilterAll PullRequestStateFilter = "all"
	PullRequestStateFilterClosed PullRequestStateFilter = "closed"
	PullRequestStateFilterOpen PullRequestStateFilter = "open"
)

// UserType представляет возможные значения для UserType
type UserType string

const (
	UserTypeOrganization UserType = "Organization"
	UserTypeUser UserType = "User"
)

// VisibilityType представляет возможные значения для VisibilityType
type VisibilityType string

const (
	VisibilityTypeLimited VisibilityType = "limited"
	VisibilityTypePrivate VisibilityType = "private"
	VisibilityTypePublic VisibilityType = "public"
)
