// Code generated by gitverse-codegen. DO NOT EDIT.

package gitverse

import (
	"context"
	"fmt"
)

// CreateDeployment Creates a deployment for GitVerse Pages
func (c *Client) CreateDeployment(ctx context.Context, owner string, repo string, params CreatePagesDeploymentParams) (PagesDeployment, error) {
	path := fmt.Sprintf("/repos/%s/%s/pages/deployments", owner, repo)
	resp, err := c.post(ctx, path, params)
	if err != nil {
		var zero PagesDeployment
		return zero, err
	}
	return decodeResponse[PagesDeployment](resp)
}

// GetDeploymentStatus Gets the status of a GitVerse Pages deployment
func (c *Client) GetDeploymentStatus(ctx context.Context, owner string, repo string, pages_deployment_id string) (PagesDeploymentStatus, error) {
	path := fmt.Sprintf("/repos/%s/%s/pages/deployments/%s", owner, repo, pages_deployment_id)
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		var zero PagesDeploymentStatus
		return zero, err
	}
	return decodeResponse[PagesDeploymentStatus](resp)
}
