// Code generated by gitverse-codegen. DO NOT EDIT.

package gitverse

import (
	"context"
	"fmt"
	"net/url"
)

// Create Create a pull request
func (c *Client) Create(ctx context.Context, owner string, repo string, params CreatePullRequestParams) (PullRequest, error) {
	path := fmt.Sprintf("/repos/%s/%s/pulls", owner, repo)
	resp, err := c.post(ctx, path, params)
	if err != nil {
		var zero PullRequest
		return zero, err
	}
	return decodeResponse[PullRequest](resp)
}

// ListCommitsPullRequests List pull request commits
func (c *Client) ListCommitsPullRequests(ctx context.Context, owner string, repo string, pull_number float64, opts *QueryOptions) ([]Commit, error) {
	path := fmt.Sprintf("/repos/%s/%s/pulls/%v/commits", owner, repo, pull_number)
	query := url.Values{}
	if opts != nil {
		if opts.Page != 0 {
			query.Set("page", fmt.Sprintf("%d", opts.Page))
		}
		if opts.PerPage != 0 {
			query.Set("per_page", fmt.Sprintf("%d", opts.PerPage))
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero []Commit
		return zero, err
	}
	return decodeResponse[[]Commit](resp)
}

// ListFiles List pull request files
func (c *Client) ListFiles(ctx context.Context, owner string, repo string, pull_number float64, opts *QueryOptions) ([]CommitFiles, error) {
	path := fmt.Sprintf("/repos/%s/%s/pulls/%v/files", owner, repo, pull_number)
	query := url.Values{}
	if opts != nil {
		if opts.Page != 0 {
			query.Set("page", fmt.Sprintf("%d", opts.Page))
		}
		if opts.PerPage != 0 {
			query.Set("per_page", fmt.Sprintf("%d", opts.PerPage))
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero []CommitFiles
		return zero, err
	}
	return decodeResponse[[]CommitFiles](resp)
}

// IsMerged Checks if a pull request has been merged into the base branch.
func (c *Client) IsMerged(ctx context.Context, owner string, repo string, pull_number float64) error {
	path := fmt.Sprintf("/repos/%s/%s/pulls/%v/merge", owner, repo, pull_number)
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// UpdateBranch Update a pull request branch
func (c *Client) UpdateBranch(ctx context.Context, owner string, repo string, pull_number float64, params UpdateBranchParams) (UpdateBranchResponse, error) {
	path := fmt.Sprintf("/repos/%s/%s/pulls/%v/update-branch", owner, repo, pull_number)
	resp, err := c.put(ctx, path, params)
	if err != nil {
		var zero UpdateBranchResponse
		return zero, err
	}
	return decodeResponse[UpdateBranchResponse](resp)
}
