// Code generated by gitverse-codegen. DO NOT EDIT.

package gitverse

import (
	"context"
	"fmt"
	"net/url"
)

// ListFavorites Get list of favorites repositories of authenticated user
func (c *Client) ListFavorites(ctx context.Context, opts *QueryOptions) ([]Repository, error) {
	path := "/user/starred"
	query := url.Values{}
	if opts != nil {
		if opts.Page != 0 {
			query.Set("page", fmt.Sprintf("%d", opts.Page))
		}
		if opts.PerPage != 0 {
			query.Set("per_page", fmt.Sprintf("%d", opts.PerPage))
		}
		if opts.Sort != "" {
			query.Set("sort", opts.Sort)
		}
		if opts.Direction != "" {
			query.Set("direction", opts.Direction)
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero []Repository
		return zero, err
	}
	return decodeResponse[[]Repository](resp)
}

// IsStarred Check if repository is in favorites
func (c *Client) IsStarred(ctx context.Context, owner string, repo string) error {
	path := fmt.Sprintf("/user/starred/%s/%s", owner, repo)
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// Star Add repository to favorites
func (c *Client) Star(ctx context.Context, owner string, repo string) error {
	path := fmt.Sprintf("/user/starred/%s/%s", owner, repo)
	resp, err := c.put(ctx, path, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}

// Unstar Remove repository from favorites
func (c *Client) Unstar(ctx context.Context, owner string, repo string) error {
	path := fmt.Sprintf("/user/starred/%s/%s", owner, repo)
	resp, err := c.delete(ctx, path, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}
