// Code generated by gitverse-codegen. DO NOT EDIT.

package gitverse

import (
	"context"
	"fmt"
	"net/url"
)

// List Lists teams
func (c *Client) List(ctx context.Context, org string, opts *QueryOptions) ([]Team, error) {
	path := fmt.Sprintf("/orgs/%s/teams", org)
	query := url.Values{}
	if opts != nil {
		if opts.Page != 0 {
			query.Set("page", fmt.Sprintf("%d", opts.Page))
		}
		if opts.PerPage != 0 {
			query.Set("per_page", fmt.Sprintf("%d", opts.PerPage))
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero []Team
		return zero, err
	}
	return decodeResponse[[]Team](resp)
}

// ListMembers Lists team members
func (c *Client) ListMembers(ctx context.Context, org string, team string, opts *QueryOptions) ([]User, error) {
	path := fmt.Sprintf("/orgs/%s/teams/%s/members", org, team)
	query := url.Values{}
	if opts != nil {
		if opts.Page != 0 {
			query.Set("page", fmt.Sprintf("%d", opts.Page))
		}
		if opts.PerPage != 0 {
			query.Set("per_page", fmt.Sprintf("%d", opts.PerPage))
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero []User
		return zero, err
	}
	return decodeResponse[[]User](resp)
}

// UpdateRepos Add or update team repository permissions
func (c *Client) UpdateRepos(ctx context.Context, org string, team string, owner string, repo string, params TeamRepoPermissions) error {
	path := fmt.Sprintf("/orgs/%s/teams/%s/repos/%s/%s", org, team, owner, repo)
	resp, err := c.put(ctx, path, params)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return parseAPIError(resp)
	}
	return nil
}
