// Code generated by gitverse-codegen. DO NOT EDIT.

package gitverse

// QueryOptions содержит опции для запросов с пагинацией и фильтрацией
type QueryOptions struct {
	// Пагинация
	Page    int
	PerPage int

	// Общие фильтры
	State     string
	Sort      string
	Direction string
	Order     string
	Type      string
	Scope     string

	// Поиск
	Q string

	// Git параметры
	Ref       string
	Sha       string
	Path      string
	Branch    string
	Tag       string
	Base      string
	Head      string
	Recursive bool

	// Pull Request фильтры
	Draft bool

	// Issue фильтры
	Labels      string
	Milestones  string
	AssignedBy  string
	MentionedBy string
	CreatedBy   string
	Author      string
	Committer   string

	// Даты
	Since  string
	Until  string
	Before string

	// Repository фильтры
	Affiliation string
	Permission  string
	Not         string

	// Actions/Releases
	Name           string
	PreRelease     bool
	EncryptedValue string
}

// PaginationInfo содержит информацию о пагинации
type PaginationInfo struct {
	Page       int
	PerPage    int
	Total      int
	TotalPages int
}

type AddCollaboratorParams struct {
	Permission *string `json:"permission,omitempty"` // enum: read,write,admin
}

type CommitUserParams struct {
	Date *string `json:"date,omitempty"`
	Email string `json:"email"`
	Name string `json:"name"`
}

type CreateActionLinkParams struct {
	Description *string `json:"description,omitempty"`
	Link *string `json:"link,omitempty"`
	Name *string `json:"name,omitempty"`
	RunId *float64 `json:"run_id,omitempty"`
}

type CreateCommitParams struct {
	Author *CommitUserParams `json:"author,omitempty"`
	Committer *CommitUserParams `json:"committer,omitempty"`
	Message string `json:"message"`
	Parents []string `json:"parents,omitempty"`
	Tree string `json:"tree"`
}

type CreateEmailParams struct {
	Emails []string `json:"emails,omitempty"`
}

type CreateFileParams struct {
	Branch *string `json:"branch,omitempty"` // ветка на которой будет базировать коммит, если пустая то будет использована ветка по умолчанию
	Content *string `json:"content,omitempty"` // content must be base64 encoded
	FromPath *string `json:"from_path,omitempty"` // SHA string `json:"sha" binding:"Required"`
	Message *string `json:"message,omitempty"` // Сообщение для описания коммита, если пустое то будет использовано сообщение по умолчанию
	NewBranch *string `json:"new_branch,omitempty"` // новая ветка которая будет отведена от указанной выше ветки и вней будет создан новый коммит
	Sha *string `json:"sha,omitempty"` // sha is the SHA for the file that already exists
	Signoff *bool `json:"signoff,omitempty"` // Подписывать ли коммит
}

type CreatePagesDeploymentParams struct {
	ArtifactId *float64 `json:"artifact_id,omitempty"`
}

type CreatePullRequestParams struct {
	Assignees []string `json:"assignees,omitempty"` // список ответственных
	Base *string `json:"base,omitempty"` // ветка в которую происходит слияние
	Body *string `json:"body,omitempty"` // тело запроса
	Draft *bool `json:"draft,omitempty"` // черновик
	DueDate *string `json:"due_date,omitempty"` // Deadline
	Head *string `json:"head,omitempty"` // ветка из которой происходит слияние
	HeadRepo *string `json:"head_repo,omitempty"` // ветка из которой происходит слияние
	Labels []float64 `json:"labels,omitempty"` // Метки
	MaintainerCanModify *bool `json:"maintainer_can_modify,omitempty"` // могут ли мэйнтейнеры изменять PR
	Milestone *float64 `json:"milestone,omitempty"` // идентификатор "этапа"
	Title *string `json:"title,omitempty"` // заголовок запроса
}

type CreateReferenceParams struct {
	Ref *string `json:"ref,omitempty"`
	Sha *string `json:"sha,omitempty"`
}

type CreateReleaseParams struct {
	Body *string `json:"body,omitempty"`
	Draft *bool `json:"draft,omitempty"`
	Name *string `json:"name,omitempty"`
	Prerelease *bool `json:"prerelease,omitempty"`
	TagName *string `json:"tag_name,omitempty"`
	TargetCommitish *string `json:"target_commitish,omitempty"`
}

type CreateRepositoryParams struct {
	AutoInit *bool `json:"auto_init,omitempty"`
	Description *string `json:"description,omitempty"`
	Gitignores []string `json:"gitignores,omitempty"`
	IsTemplate *bool `json:"is_template,omitempty"`
	Name *string `json:"name,omitempty"`
	Private *bool `json:"private,omitempty"`
}

type TreeItem struct {
	Content *string `json:"content,omitempty"`
	Mode *string `json:"mode,omitempty"`
	Path *string `json:"path,omitempty"`
	Sha *string `json:"sha,omitempty"`
	Type *string `json:"type,omitempty"`
}

type CreateTreeParams struct {
	BaseTree *string `json:"base_tree,omitempty"`
	Tree []TreeItem `json:"tree,omitempty"`
}

type CreateVariableParams struct {
	Name *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

type DeleteEmailParams struct {
	Emails []string `json:"emails,omitempty"`
}

type DeleteFileParams struct {
	Branch *string `json:"branch,omitempty"` // ветка на которой будет базировать коммит, если пустая то будет использована ветка по умолчанию
	Message *string `json:"message,omitempty"` // Сообщение для описания коммита, если пустое то будет использовано сообщение по умолчанию
	NewBranch *string `json:"new_branch,omitempty"` // новая ветка которая будет отведена от указанной выше ветки и вней будет создан новый коммит
	Sha *string `json:"sha,omitempty"` // sha is the SHA for the file that already exists
	Signoff *bool `json:"signoff,omitempty"` // Подписывать ли коммит
}

type UpdateReleaseParams struct {
	Body *string `json:"body,omitempty"`
	Draft *bool `json:"draft,omitempty"`
	Name *string `json:"name,omitempty"`
	Prerelease *bool `json:"prerelease,omitempty"`
	TagName *string `json:"tag_name,omitempty"`
	TargetCommitish *string `json:"target_commitish,omitempty"`
}

type CreateForkParams struct {
	Description *string `json:"description,omitempty"` // Описание
	Name *string `json:"name,omitempty"` // Имя форкнутого репозитория
	Organization *string `json:"organization,omitempty"` // Название организации, если форкаем в организацию
}

type UpdateRepositoryParams struct {
	AllowAutoMerge *bool `json:"allow_auto_merge,omitempty"`
	AllowMerge *bool `json:"allow_merge,omitempty"`
	AllowRebase *bool `json:"allow_rebase,omitempty"`
	AllowRebaseMerge *bool `json:"allow_rebase_merge,omitempty"`
	AllowSquashMerge *bool `json:"allow_squash_merge,omitempty"`
	AllowUpdateBranch *bool `json:"allow_update_branch,omitempty"`
	Archived *bool `json:"archived,omitempty"`
	AutodetectManualMerge *bool `json:"autodetect_manual_merge,omitempty"`
	DefaultAllowMaintainerEdit *bool `json:"default_allow_maintainer_edit,omitempty"`
	DefaultBranch *string `json:"default_branch,omitempty"`
	DefaultMergeStyle *string `json:"default_merge_style,omitempty"`
	DeleteBranchOnMerge *bool `json:"delete_branch_on_merge,omitempty"`
	Description *string `json:"description,omitempty"`
	Homepage *string `json:"homepage,omitempty"`
	IgnoreWhitespace *bool `json:"ignore_whitespace,omitempty"`
	IsTemplate *bool `json:"is_template,omitempty"`
	Name *string `json:"name,omitempty"` // обработаны
	Private *bool `json:"private,omitempty"`
}

type TeamRepoPermissions struct {
	Permission *string `json:"permission,omitempty"`
}

type UpdateBranchParams struct {
	ExpectedHeadSha *string `json:"expected_head_sha,omitempty"`
}

type UpdatePullRequestParams struct {
	Base *string `json:"base,omitempty"` // ветка в которую происходит слияние
	Body *string `json:"body,omitempty"` // тело запроса
	MaintainerCanModify *bool `json:"maintainer_can_modify,omitempty"` // могут ли мэйнтейнеры изменять PR
	State *string `json:"state,omitempty"` // статус запроса
	Title *string `json:"title,omitempty"` // заголовок запроса
}

type ActionWorkflowRun struct {
	HeadSha *string `json:"head_sha,omitempty"`
	Id *float64 `json:"id,omitempty"`
	RepositoryId *float64 `json:"repository_id,omitempty"`
}

type ActionArtifact struct {
	ArchiveDownloadUrl *string `json:"archive_download_url,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Expired *bool `json:"expired,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
	Id *float64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	SizeInBytes *float64 `json:"size_in_bytes,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	Url *string `json:"url,omitempty"`
	WorkflowRun *ActionWorkflowRun `json:"workflow_run,omitempty"`
}

type ActionArtifactList struct {
	Artifacts []ActionArtifact `json:"artifacts,omitempty"`
	TotalCount *float64 `json:"total_count,omitempty"`
}

type ActionLink struct {
	Description *string `json:"description,omitempty"`
	Id *float64 `json:"id,omitempty"`
	Link *string `json:"link,omitempty"`
	Name *string `json:"name,omitempty"`
	RunId *float64 `json:"run_id,omitempty"`
}

type ActionRunnerLabel struct {
	Id *float64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

type ActionRunner struct {
	Busy *bool `json:"busy,omitempty"`
	Id *float64 `json:"id,omitempty"`
	Labels []ActionRunnerLabel `json:"labels,omitempty"`
	Name *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

type ActionRunners struct {
	Runners []ActionRunner `json:"runners,omitempty"`
	TotalCount *float64 `json:"total_count,omitempty"`
}

type Attachment struct {
	BrowserDownloadUrl *string `json:"browser_download_url,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	DownloadCount *float64 `json:"download_count,omitempty"`
	Id *float64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Size *float64 `json:"size,omitempty"`
	Uuid *string `json:"uuid,omitempty"`
}

type CommitMeta struct {
	Created *string `json:"created,omitempty"`
	HtmlUrl *string `json:"html_url,omitempty"`
	Sha *string `json:"sha,omitempty"`
	Url *string `json:"url,omitempty"`
}

type Branch struct {
	Commit CommitMeta `json:"commit"` // Информация о последнем коммите в ветке
	Name string `json:"name"` // Имя ветки
	Protected bool `json:"protected"` // Является ли ветка защищенной
}

type Permissions struct {
	Admin *bool `json:"admin,omitempty"`
	Pull *bool `json:"pull,omitempty"`
	Push *bool `json:"push,omitempty"`
}

type Collaborator struct {
	AvatarUrl string `json:"avatar_url"` // Ссылка на аватар
	Bio *string `json:"bio,omitempty"` // О себе
	Email *string `json:"email,omitempty"` // Почта
	FollowersUrl *string `json:"followers_url,omitempty"` // Url для получения подписчиков пользователя
	FollowingUrl *string `json:"following_url,omitempty"` // Url для получения подписок пользователя
	FullName *string `json:"full_name,omitempty"` // Полное имя
	HtmlUrl string `json:"html_url"` // Ссылка на профиль в веб-интерфейсе
	Id float64 `json:"id"` // Уникальный идентификатор
	Login string `json:"login"` // Логин пользователя
	Name *string `json:"name,omitempty"` // Имя пользователя
	OrganizationsUrl *string `json:"organizations_url,omitempty"` // Url для получения организаций пользователя
	Permissions Permissions `json:"permissions"` // Права доступа к репозиторию
	ReposUrl *string `json:"repos_url,omitempty"` // Url для получения репозиториев пользователя
	SiteAdmin bool `json:"site_admin"` // Является ли пользователь администратором платформы
	StarredUrl *string `json:"starred_url,omitempty"` // Url для получения репозиториев пользователя, которые были добавлены в избранное
	SubscriptionsUrl *string `json:"subscriptions_url,omitempty"` // Url для получения подписок пользователя
	Type string `json:"type"` // Тип аккаунта (User или Organization)
	Url *string `json:"url,omitempty"` // Url для получения пользователя
	Website *string `json:"website,omitempty"` // Вебсайт
}

type UserPublicInfo struct {
	AvatarUrl string `json:"avatar_url"` // Ссылка на аватар
	FollowersUrl string `json:"followers_url"` // Ссылка на список подписчиков пользователя
	FollowingUrl string `json:"following_url"` // Ссылка на список пользователей, на которых подписан текущий пользователь
	HtmlUrl string `json:"html_url"` // Ссылка на профиль в веб-интерфейсе
	Id float64 `json:"id"` // Уникальный идентификатор пользователя
	Login string `json:"login"` // Логин (уникальное имя)
	OrganizationsUrl string `json:"organizations_url"` // Ссылка на список организаций, в которых состоит пользователь
	ReposUrl string `json:"repos_url"` // Ссылка на список репозиториев пользователя
	SiteAdmin bool `json:"site_admin"` // Является ли пользователь администратором платформы
	Type string `json:"type"` // Тип: "user" или "organization"
	Url string `json:"url"` // API-ссылка на пользователя
}

type RepoPublicInfo struct {
	ContentsUrl *string `json:"contents_url,omitempty"`
	Description *string `json:"description,omitempty"`
	Fork *bool `json:"fork,omitempty"`
	ForksUrl *string `json:"forks_url,omitempty"`
	FullName *string `json:"full_name,omitempty"`
	HtmlUrl *string `json:"html_url,omitempty"`
	Id *float64 `json:"id,omitempty"`
	IssueCommentUrl *string `json:"issue_comment_url,omitempty"`
	IssuesUrl *string `json:"issues_url,omitempty"`
	LanguagesUrl *string `json:"languages_url,omitempty"`
	Name *string `json:"name,omitempty"`
	Owner *UserPublicInfo `json:"owner,omitempty"`
	Private *bool `json:"private,omitempty"`
	PullsUrl *string `json:"pulls_url,omitempty"`
	Url *string `json:"url,omitempty"`
}

type CollaboratorInvitation struct {
	CreatedAt *string `json:"created_at,omitempty"`
	Id *float64 `json:"id,omitempty"`
	Invitee *UserPublicInfo `json:"invitee,omitempty"`
	Inviter *UserPublicInfo `json:"inviter,omitempty"`
	Permissions *string `json:"permissions,omitempty"`
	Repository *RepoPublicInfo `json:"repository,omitempty"`
}

type Comment struct {
	AuthorAssociation string `json:"author_association"` // Роль автора относительно репозитория: OWNER, MEMBER, CONTRIBUTOR, NONE
	Body string `json:"body"` // Текст комментария
	CreatedAt string `json:"created_at"` // Дата создания (ISO 8601)
	HtmlUrl string `json:"html_url"` // Ссылка на комментарий в веб-интерфейсе
	Id float64 `json:"id"` // Уникальный идентификатор комментария
	IssueUrl string `json:"issue_url"` // Ссылка на задачу или пул-реквест
	UpdatedAt string `json:"updated_at"` // Дата последнего изменения (ISO 8601)
	Url *string `json:"url,omitempty"` // Url для получения пользователя
	User UserPublicInfo `json:"user"` // Информация об авторе комментария
}

type CommitFiles struct {
	Additions *float64 `json:"additions,omitempty"`
	BlobUrl *string `json:"blob_url,omitempty"`
	Changes *float64 `json:"changes,omitempty"`
	ContentsUrl *string `json:"contents_url,omitempty"`
	Deletions *float64 `json:"deletions,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Patch *string `json:"patch,omitempty"`
	RawUrl *string `json:"raw_url,omitempty"`
	Sha *string `json:"sha,omitempty"`
	Status *string `json:"status,omitempty"`
}

type CommitUser struct {
	Date *string `json:"date,omitempty"`
	Email *string `json:"email,omitempty"`
	Name *string `json:"name,omitempty"`
}

type TreeMeta struct {
	Created *string `json:"created,omitempty"`
	Sha *string `json:"sha,omitempty"`
	Url *string `json:"url,omitempty"`
}

type RepoCommit struct {
	Author CommitUser `json:"author"` // Нет
	Committer CommitUser `json:"committer"` // Нет
	Message string `json:"message"` // Да
	Tree TreeMeta `json:"tree"` // Да
	Url *string `json:"url,omitempty"`
}

type CommitStats struct {
	Additions *float64 `json:"additions,omitempty"`
	Deletions *float64 `json:"deletions,omitempty"`
	Total *float64 `json:"total,omitempty"`
}

type Commit struct {
	Author *UserPublicInfo `json:"author,omitempty"`
	Branch *string `json:"branch,omitempty"`
	Commit *RepoCommit `json:"commit,omitempty"`
	Committer *UserPublicInfo `json:"committer,omitempty"`
	Created *string `json:"created,omitempty"`
	Files []CommitFiles `json:"files,omitempty"`
	HtmlUrl *string `json:"html_url,omitempty"`
	Parents []CommitMeta `json:"parents,omitempty"`
	Sha string `json:"sha"` // Хеш коммита (обязательный)
	Stats *CommitStats `json:"stats,omitempty"`
	Url *string `json:"url,omitempty"`
}

type CommitVerification struct {
	Payload *string `json:"payload,omitempty"`
	Reason *string `json:"reason,omitempty"`
	Signature *string `json:"signature,omitempty"`
	Verified *bool `json:"verified,omitempty"`
	VerifiedAt *string `json:"verifiedAt,omitempty"`
}

type CompareResponse struct {
	AheadBy *float64 `json:"ahead_by,omitempty"`
	BaseCommit *Commit `json:"base_commit,omitempty"`
	BehindBy *float64 `json:"behind_by,omitempty"`
	Commits []Commit `json:"commits,omitempty"`
	Files []CommitFiles `json:"files,omitempty"`
	HtmlUrl *string `json:"html_url,omitempty"`
	MergeBaseCommit *Commit `json:"merge_base_commit,omitempty"`
	Status *string `json:"status,omitempty"`
	TotalCommits *float64 `json:"total_commits,omitempty"`
	Url *string `json:"url,omitempty"`
}

type FileLinksResponse struct {
	Git *string `json:"git,omitempty"`
	Html *string `json:"html,omitempty"`
	Self *string `json:"self,omitempty"`
}

type ContentsResponse struct {
	Links FileLinksResponse `json:"_links"` // Объект со ссылками: self, git, html
	Content *string `json:"content,omitempty"` // Содержимое файла в Base64 (только для type: "file")
	DownloadUrl *string `json:"download_url,omitempty"` // Прямая ссылка для скачивания (null для директорий)
	Encoding string `json:"encoding"` // Кодировка содержимого (base64 для файлов)
	GitUrl string `json:"git_url"` // Ссылка на Git-объект (blob/tree)
	HtmlUrl string `json:"html_url"` // Ссылка на веб-интерфейс
	Language *string `json:"language,omitempty"` // Язык программирования (если применимо)
	Name string `json:"name"` // Имя файла или папки
	Path string `json:"path"` // Полный путь от корня репозитория
	Sha string `json:"sha"` // SHA-хеш объекта Git
	Size float64 `json:"size"` // Размер в байтах (для директорий — 0)
	SubmoduleGitUrl *string `json:"submodule_git_url,omitempty"` // `submodule_git_url` is populated when `type` is `submodule`, otherwise null
	Target *string `json:"target,omitempty"` // `target` is populated when `type` is `symlink`, otherwise null
	Type string `json:"type"` // Тип: "file", "dir", "symlink" или "submodule"
	Url string `json:"url"` // API-ссылка на этот объект
}

type FileCommitResponse struct {
	Author *CommitUser `json:"author,omitempty"`
	Committer *CommitUser `json:"committer,omitempty"`
	Created *string `json:"created,omitempty"`
	HtmlUrl *string `json:"html_url,omitempty"`
	Message *string `json:"message,omitempty"`
	Parents []CommitMeta `json:"parents,omitempty"`
	Sha *string `json:"sha,omitempty"`
	Tree *CommitMeta `json:"tree,omitempty"`
	Url *string `json:"url,omitempty"`
	Verification *CommitVerification `json:"verification,omitempty"`
}

type FileCreationResponse struct {
	Commit *FileCommitResponse `json:"commit,omitempty"`
	Content ContentsResponse `json:"content"` // Да
}

type FileDeleteResponse struct {
	Commit *FileCommitResponse `json:"commit,omitempty"`
	Content *interface{} `json:"content,omitempty"`
}

type Email struct {
	Email string `json:"email"` // Email-адрес
	Primary bool `json:"primary"` // Является ли основным адресом аккаунта
	Verified bool `json:"verified"` // Подтвержден ли адрес (через email-верификацию)
	Visibility string `json:"visibility"` // Видимость: public или private
}

type GitEntry struct {
	Mode *string `json:"mode,omitempty"`
	Path *string `json:"path,omitempty"`
	Sha *string `json:"sha,omitempty"`
	Size *float64 `json:"size,omitempty"`
	Type *string `json:"type,omitempty"`
	Url *string `json:"url,omitempty"`
}

type GitObject struct {
	Sha *string `json:"sha,omitempty"`
	Type *string `json:"type,omitempty"`
	Url *string `json:"url,omitempty"`
}

type GitTreeResponse struct {
	Page float64 `json:"page"` // Текущая страница пагинации
	Sha string `json:"sha"` // SHA-хеш запрошенного дерева
	TotalCount float64 `json:"total_count"` // Общее количество элементов в дереве
	Tree []GitEntry `json:"tree"` // Список элементов (файлов и папок)
	Truncated bool `json:"truncated"` // Был ли результат обрезан из-за ограничений (например, слишком большое дерево)
	Url string `json:"url"` // API-ссылка на это дерево
}

type User struct {
	AvatarUrl *string `json:"avatar_url,omitempty"` // Адрес аватарки
	Bio *string `json:"bio,omitempty"` // О себе
	CreatedAt *string `json:"created_at,omitempty"` // Дата создания учетной записи
	Email *string `json:"email,omitempty"` // Почта
	Followers *float64 `json:"followers,omitempty"` // Счетчики
	FollowersUrl *string `json:"followers_url,omitempty"` // Url для получения подписчиков пользователя
	Following *float64 `json:"following,omitempty"`
	FollowingUrl *string `json:"following_url,omitempty"` // Url для получения подписок пользователя
	FullName *string `json:"full_name,omitempty"` // Полное имя
	HtmlUrl *string `json:"html_url,omitempty"` // Адрес страницы пользователя
	Id *float64 `json:"id,omitempty"` // Идентификатор
	IsVerified *bool `json:"is_verified,omitempty"` // Верифицирован?
	Location *string `json:"location,omitempty"` // Местоположение
	Login *string `json:"login,omitempty"` // Логин пользователя
	Name *string `json:"name,omitempty"` // Имя пользователя
	OrganizationsUrl *string `json:"organizations_url,omitempty"` // Url для получения организаций пользователя
	PublicRepos *float64 `json:"public_repos,omitempty"` // Публичные репозитории
	ReposUrl *string `json:"repos_url,omitempty"` // Url для получения репозиториев пользователя
	SiteAdmin *bool `json:"site_admin,omitempty"` // Есть ли права админа
	StarredUrl *string `json:"starred_url,omitempty"` // Url для получения репозиториев пользователя, которые были добавлены в избранное
	StarsCount *float64 `json:"stars_count,omitempty"` // Количество репозиториев в избранном
	SubscriptionsUrl *string `json:"subscriptions_url,omitempty"` // Url для получения подписок пользователя
	Type *string `json:"type,omitempty"` // Тип пользователя
	UpdatedAt *string `json:"updated_at,omitempty"` // Дата изменения учетной записи
	Url *string `json:"url,omitempty"` // Url для получения пользователя
	Website *string `json:"website,omitempty"` // Вебсайт
}

type Label struct {
	Color string `json:"color"` // Цвет метки в формате HEX (без #)
	Description string `json:"description"` // Описание метки
	Exclusive bool `json:"exclusive"` // Является ли метка исключающей (только одна из группы)
	Id float64 `json:"id"` // Уникальный идентификатор метки
	IsArchived bool `json:"is_archived"` // Архивирована ли метка
	Name string `json:"name"` // Название метки
	Url string `json:"url"` // Ссылка на метку в API
}

type Milestone struct {
	ClosedAt *string `json:"closed_at,omitempty"`
	ClosedIssues *float64 `json:"closed_issues,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Description *string `json:"description,omitempty"`
	DueOn *string `json:"due_on,omitempty"`
	Id *float64 `json:"id,omitempty"`
	OpenIssues *float64 `json:"open_issues,omitempty"`
	State *string `json:"state,omitempty"`
	Title *string `json:"title,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

type PullRequestMeta struct {
	Draft *bool `json:"draft,omitempty"`
	HtmlUrl *string `json:"html_url,omitempty"`
	Merged *bool `json:"merged,omitempty"`
	MergedAt *string `json:"merged_at,omitempty"`
}

type RepositoryMeta struct {
	FullName *string `json:"full_name,omitempty"`
	Id *float64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Owner *string `json:"owner,omitempty"`
}

type Issue struct {
	Assets []Attachment `json:"assets,omitempty"`
	Assignee *User `json:"assignee,omitempty"`
	Assignees []User `json:"assignees"` // Список назначенных пользователей
	Body string `json:"body"` // Описание
	ClosedAt *string `json:"closed_at,omitempty"` // Дата закрытия (если закрыта)
	Comments float64 `json:"comments"` // Количество комментариев
	CreatedAt string `json:"created_at"` // Дата создания (ISO 8601)
	DueDate *string `json:"due_date,omitempty"`
	HtmlUrl string `json:"html_url"` // Ссылка на задачу в веб-интерфейсе
	Id float64 `json:"id"` // Внутренний ID задачи
	IsLocked *bool `json:"is_locked,omitempty"`
	Labels []Label `json:"labels"` // Список меток
	Milestone *Milestone `json:"milestone,omitempty"` // Веха (milestone)
	Number float64 `json:"number"` // Публичный индекс задачи/PR в репозитории
	OriginalAuthor *string `json:"original_author,omitempty"`
	OriginalAuthorId *float64 `json:"original_author_id,omitempty"`
	PullRequest *PullRequestMeta `json:"pull_request,omitempty"` // Присутствует только для пул-реквестов
	Ref *string `json:"ref,omitempty"`
	Repository *RepositoryMeta `json:"repository,omitempty"`
	State string `json:"state"` // Состояние: open, closed
	Title string `json:"title"` // Заголовок
	UpdatedAt string `json:"updated_at"` // Дата последнего изменения
	Url *string `json:"url,omitempty"`
	User User `json:"user"` // Автор задачи
}

type PagesDeployment struct {
	Id *float64 `json:"id,omitempty"`
	PageUrl *string `json:"page_url,omitempty"`
	StatusUrl *string `json:"status_url,omitempty"`
}

type PagesDeploymentStatus struct {
	Status *string `json:"status,omitempty"`
}

type Repository struct {
	AllowMergeCommit bool `json:"allow_merge_commit"` // Разрешено ли создание merge-коммитов
	AllowRebaseMerge bool `json:"allow_rebase_merge"` // Разрешено ли rebase-слияние
	AllowSquashMerge bool `json:"allow_squash_merge"` // Разрешено ли squash-слияние
	Archived bool `json:"archived"` // Архивирован ли репозиторий
	CloneUrl string `json:"clone_url"` // Ссылка для клонирования по HTTPS
	ContentsUrl *string `json:"contents_url,omitempty"`
	CreatedAt string `json:"created_at"` // Дата и время создания (ISO 8601)
	DefaultBranch string `json:"default_branch"` // Имя основной ветки
	DeleteBranchOnMerge bool `json:"delete_branch_on_merge"` // Удалять ли ветку после слияния
	Description *string `json:"description,omitempty"` // Описание репозитория
	Disabled bool `json:"disabled"` // Отключен ли репозиторий
	Fork bool `json:"fork"` // Является ли репозиторий форком
	Forks *float64 `json:"forks,omitempty"`
	ForksCount float64 `json:"forks_count"` // Количество форков
	ForksUrl *string `json:"forks_url,omitempty"`
	FullName string `json:"full_name"` // Полное имя репозитория (owner/repo)
	HasIssues bool `json:"has_issues"` // Включены ли задачи (issues)
	HasWiki bool `json:"has_wiki"` // Включена ли вики
	Id float64 `json:"id"` // Уникальный числовой идентификатор репозитория
	IsTemplate bool `json:"is_template"` // Является ли репозиторий шаблоном
	IssueCommentUrl *string `json:"issue_comment_url,omitempty"`
	IssuesUrl *string `json:"issues_url,omitempty"`
	Language *string `json:"language,omitempty"` // Основной язык программирования
	LanguagesUrl *string `json:"languages_url,omitempty"`
	MirrorUrl *string `json:"mirror_url,omitempty"`
	Name string `json:"name"` // Название репозитория
	OpenIssues *float64 `json:"open_issues,omitempty"`
	OpenIssuesCount float64 `json:"open_issues_count"` // Количество открытых задач и PR
	Owner UserPublicInfo `json:"owner"` // Информация о владельце: login (строка), id (целое число), avatar_url (строка)
	Parent *Repository `json:"parent,omitempty"`
	Permissions Permissions `json:"permissions"` // Права текущего пользователя: admin, push, pull (все — boolean)
	Private bool `json:"private"` // Признак приватности: true — приватный, false — публичный
	PullsUrl *string `json:"pulls_url,omitempty"`
	PushedAt string `json:"pushed_at"` // Дата последнего пуша
	Size float64 `json:"size"` // Размер репозитория в килобайтах
	SshUrl string `json:"ssh_url"` // Ссылка для клонирования по SSH
	StargazersCount float64 `json:"stargazers_count"` // Количество пользователей, поставивших «звезду»
	TemplateRepository *Repository `json:"template_repository,omitempty"`
	Topics []string `json:"topics"` // Список тем (тегов) репозитория
	UpdatedAt string `json:"updated_at"` // Дата последнего обновления метаданных
	Url *string `json:"url,omitempty"`
	Visibility string `json:"visibility"` // Видимость: public, private или internal
	Watchers *float64 `json:"watchers,omitempty"`
	WatchersCount float64 `json:"watchers_count"` // Количество наблюдателей
}

type PRBranchInfo struct {
	Label *string `json:"label,omitempty"`
	Ref *string `json:"ref,omitempty"`
	Repo *Repository `json:"repo,omitempty"`
	RepoId *float64 `json:"repo_id,omitempty"`
	Sha *string `json:"sha,omitempty"`
}

type Team struct {
	CanCreateOrgRepo *bool `json:"can_create_org_repo,omitempty"` // Полномочия на создание репозиториев
	Description *string `json:"description,omitempty"` // Описание команды (может быть null)
	Id float64 `json:"id"` // Уникальный идентификатор команды
	IncludesAllRepositories *bool `json:"includes_all_repositories,omitempty"` // Включает все репозитории
	Name string `json:"name"` // Название команды
	NumMembers *float64 `json:"num_members,omitempty"` // Количество участников
	NumRepos *float64 `json:"num_repos,omitempty"` // Количество репозиториев
	Permission string `json:"permission"` // Общий уровень доступа: none, read, write, admin, owner
	PermissionActions *string `json:"permission_actions,omitempty"` // Полномочие на действия с ветками
	PermissionCode *string `json:"permission_code,omitempty"` // Код полномочия
	PermissionPackages *string `json:"permission_packages,omitempty"` // Полномочие на пакеты
	PermissionPulls *string `json:"permission_pulls,omitempty"` // Полномочие на отправку пулл-реквестов
	PermissionReleases *string `json:"permission_releases,omitempty"` // Полномочие на релизы
}

type PullRequest struct {
	Assignee *User `json:"assignee,omitempty"`
	Assignees []User `json:"assignees"` // Назначенные участники
	Base PRBranchInfo `json:"base"` // Целевая ветка и репозиторий
	Body string `json:"body"` // Описание (тело) PR
	ClosedAt *string `json:"closed_at,omitempty"` // Дата закрытия (если закрыт)
	Comments float64 `json:"comments"` // Количество комментариев
	CreatedAt string `json:"created_at"` // Дата создания (RFC3339)
	DiffUrl *string `json:"diff_url,omitempty"`
	Head PRBranchInfo `json:"head"` // Исходная ветка и репозиторий
	HtmlUrl string `json:"html_url"` // Ссылка на PR в веб-интерфейсе
	Id float64 `json:"id"` // Уникальный идентификатор pull request
	IsDraft bool `json:"is_draft"` // Является ли черновиком
	Labels []Label `json:"labels"` // Метки
	Locked bool `json:"locked"` // Заблокирован ли от комментариев
	MaintainerCanModify bool `json:"maintainer_can_modify"` // Могут ли мейнтейнеры изменять ветку автора
	MergeCommitSha *string `json:"merge_commit_sha,omitempty"` // SHA коммита слияния
	Mergeable bool `json:"mergeable"` // Можно ли слить без конфликтов
	Merged bool `json:"merged"` // Был ли PR слит
	MergedAt *string `json:"merged_at,omitempty"` // Дата слияния (если слит)
	MergedBy *User `json:"merged_by,omitempty"`
	Milestone *Milestone `json:"milestone,omitempty"` // Веха (milestone)
	Number float64 `json:"number"` // Номер PR в репозитории
	PatchUrl *string `json:"patch_url,omitempty"`
	RequestedReviewers []User `json:"requested_reviewers"` // Запрошенные ревьюеры
	RequestedTeams []Team `json:"requested_teams"` // Запрошенные команды
	State string `json:"state"` // Состояние: open, closed
	Title string `json:"title"` // Заголовок PR
	UpdatedAt string `json:"updated_at"` // Дата последнего обновления
	Url string `json:"url"` // API-ссылка на PR
	User User `json:"user"` // Автор PR
}

type Reference struct {
	Object *GitObject `json:"object,omitempty"`
	Ref string `json:"ref"` // Полный путь к ссылке. Примеры: refs/heads/new-feature, refs/tags/v1.0.
	Url *string `json:"url,omitempty"`
}

type RegistrationToken struct {
	Token *string `json:"token,omitempty"`
}

type Release struct {
	Assets []Attachment `json:"assets,omitempty"`
	Author *User `json:"author,omitempty"`
	Body *string `json:"body,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Draft *bool `json:"draft,omitempty"`
	HtmlUrl *string `json:"html_url,omitempty"`
	Id *float64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Prerelease *bool `json:"prerelease,omitempty"`
	PublishedAt *string `json:"published_at,omitempty"`
	TagName *string `json:"tag_name,omitempty"`
	TarballUrl *string `json:"tarball_url,omitempty"`
	TargetCommitish *string `json:"target_commitish,omitempty"`
	UploadUrl *string `json:"upload_url,omitempty"`
	Url *string `json:"url,omitempty"`
	ZipballUrl *string `json:"zipball_url,omitempty"`
}

type TreeEntry struct {
	Mode *string `json:"mode,omitempty"`
	Path *string `json:"path,omitempty"`
	Sha *string `json:"sha,omitempty"`
	Size *float64 `json:"size,omitempty"`
	Type *string `json:"type,omitempty"` // "blob", "tree", "commit"
}

type RepoTree struct {
	Sha *string `json:"sha,omitempty"`
	Tree []TreeEntry `json:"tree"` // Да
	Truncated *bool `json:"truncated,omitempty"`
	Url *string `json:"url,omitempty"`
}

type Secret struct {
	CreatedAt *string `json:"created_at,omitempty"`
	Name *string `json:"name,omitempty"`
}

type SecretList struct {
	Secrets []Secret `json:"secrets,omitempty"`
	TotalCount *float64 `json:"total_count,omitempty"`
}

type TrackedTime struct {
	Created *string `json:"created,omitempty"` // swagger:strfmt date-time
	Id *float64 `json:"id,omitempty"`
	Issue *Issue `json:"issue,omitempty"`
	IssueId *float64 `json:"issue_id,omitempty"` // deprecated (only for backwards compatibility)
	Time *float64 `json:"time,omitempty"` // Time in seconds
	UserId *float64 `json:"user_id,omitempty"` // deprecated (only for backwards compatibility)
	UserName *string `json:"user_name,omitempty"`
}

type TimelineComment struct {
	Assignee User `json:"assignee"` // Назначенный пользователь (только для assigned/unassigned)
	AssigneeTeam *Team `json:"assignee_team,omitempty"`
	Body *string `json:"body,omitempty"` // Текст комментария (только для type: commented)
	CreatedAt string `json:"created_at"` // Дата события (RFC3339)
	DependentIssue *Issue `json:"dependent_issue,omitempty"`
	HtmlUrl string `json:"html_url"` // Ссылка на событие в веб-интерфейсе (если применимо)
	Id float64 `json:"id"` // Уникальный идентификатор события
	IssueUrl *string `json:"issue_url,omitempty"`
	Label Label `json:"label"` // Метка (только для labeled/unlabeled)
	Milestone *Milestone `json:"milestone,omitempty"`
	NewRef *string `json:"new_ref,omitempty"`
	NewTitle *string `json:"new_title,omitempty"`
	OldMilestone *Milestone `json:"old_milestone,omitempty"`
	OldProjectId *float64 `json:"old_project_id,omitempty"`
	OldRef *string `json:"old_ref,omitempty"`
	OldTitle *string `json:"old_title,omitempty"`
	ProjectId *float64 `json:"project_id,omitempty"`
	PullRequestUrl *string `json:"pull_request_url,omitempty"`
	RefAction *string `json:"ref_action,omitempty"`
	RefComment *Comment `json:"ref_comment,omitempty"`
	RefCommitSha *string `json:"ref_commit_sha,omitempty"` // commit SHA where issue/PR was referenced
	RefIssue *Issue `json:"ref_issue,omitempty"`
	RemovedAssignee *bool `json:"removed_assignee,omitempty"` // whether the assignees were removed or added
	ResolveDoer *User `json:"resolve_doer,omitempty"`
	ReviewId *float64 `json:"review_id,omitempty"`
	TrackedTime *TrackedTime `json:"tracked_time,omitempty"`
	Type string `json:"type"` // Тип события (например, commented, labeled, closed)
	UpdatedAt *string `json:"updated_at,omitempty"` // swagger:strfmt date-time
	User User `json:"user"` // Автор события
}

type UpdateBranchResponse struct {
	Message *string `json:"message,omitempty"`
	Url *string `json:"url,omitempty"`
}

type UserPrefsArray struct {
	IncompleteResults *bool `json:"incomplete_results,omitempty"`
	Items []User `json:"items,omitempty"`
	TotalCount *float64 `json:"total_count,omitempty"`
}

type Variable struct {
	CreatedAt *string `json:"created_at,omitempty"`
	Name *string `json:"name,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	Value *string `json:"value,omitempty"`
}

type VariableList struct {
	TotalCount *float64 `json:"total_count,omitempty"`
	Variables []Variable `json:"variables,omitempty"`
}

type WorkflowDispatchInput struct {
	Default *string `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Name *string `json:"name,omitempty"`
	Options []string `json:"options,omitempty"`
	Required *bool `json:"required,omitempty"`
	Type *string `json:"type,omitempty"`
}

type WorkflowDispatchInputList struct {
	Inputs []WorkflowDispatchInput `json:"inputs,omitempty"`
}
