// Code generated by gitverse-codegen. DO NOT EDIT.

package gitverse

import (
	"context"
	"fmt"
	"net/url"
)

// ListUsers Search users by query
func (c *Client) ListUsers(ctx context.Context, opts *QueryOptions) (UserPrefsArray, error) {
	path := "/search/users"
	query := url.Values{}
	if opts != nil {
		if opts.Q != "" {
			query.Set("q", opts.Q)
		}
		if opts.Sort != "" {
			query.Set("sort", opts.Sort)
		}
		if opts.Order != "" {
			query.Set("order", opts.Order)
		}
		if opts.Page != 0 {
			query.Set("page", fmt.Sprintf("%d", opts.Page))
		}
		if opts.PerPage != 0 {
			query.Set("per_page", fmt.Sprintf("%d", opts.PerPage))
		}
	}
	resp, err := c.get(ctx, path, query)
	if err != nil {
		var zero UserPrefsArray
		return zero, err
	}
	return decodeResponse[UserPrefsArray](resp)
}

// GetAuthenticated Get authenticated user information
func (c *Client) GetAuthenticated(ctx context.Context) (User, error) {
	path := "/user"
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		var zero User
		return zero, err
	}
	return decodeResponse[User](resp)
}

// GetUsers Get user information by ID
func (c *Client) GetUsers(ctx context.Context, account_id float64) (User, error) {
	path := fmt.Sprintf("/user/%v", account_id)
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		var zero User
		return zero, err
	}
	return decodeResponse[User](resp)
}

// GetByUsername Get user information by username
func (c *Client) GetByUsername(ctx context.Context, username string) (User, error) {
	path := fmt.Sprintf("/users/%s", username)
	resp, err := c.get(ctx, path, nil)
	if err != nil {
		var zero User
		return zero, err
	}
	return decodeResponse[User](resp)
}
